// <auto-generated />
namespace HURazor.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class followPrimaryKeyChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(followPrimaryKeyChange));
        
        string IMigrationMetadata.Id
        {
            get { return "201308061743034_followPrimaryKeyChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
