// <auto-generated />
namespace HURazor.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class nameEmailFollow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nameEmailFollow));
        
        string IMigrationMetadata.Id
        {
            get { return "201307251905208_nameEmailFollow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
