// <auto-generated />
namespace HURazor.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedIsFollowedProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedIsFollowedProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201308062030027_addedIsFollowedProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
