// <auto-generated />
namespace HURazor.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class userprofileFollowProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userprofileFollowProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201308052029502_userprofileFollowProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
